import type { Metadata } from 'next'
import { Caveat } from 'next/font/google'
import localFont from 'next/font/local'

import BottomTab from '@/components/layout/BottomTab'
import QueryProvider from '@/components/provider/QueryProvider'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const pretendard = localFont({
  src: [
    {
      path: '../assets/fonts/PretendardVariable.woff2',
      style: 'normal'
    }
  ],
  variable: '--font-pretendard'
})

const caveat = Caveat({
  variable: '--font-caveat',
  subsets: ['latin']
})

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ko'>
      <head>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0'
        />
      </head>
      <body
        className={`${pretendard.variable} ${caveat.variable} font-[--font-pretendard] max-w-xl mx-auto relative pb-12 h-screen`}>
        <QueryProvider>{children}</QueryProvider>
        <BottomTab />
        <script
          type='text/javascript'
          src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NAVER_CLIENT_ID}`}></script>
      </body>
    </html>
  )
}
